<a href="https://colab.research.google.com/github/Alimohd88/DATA_JOBS_DASH_POWERBI/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
!pip install -U jupysql

Requirement already satisfied: jupysql in /usr/local/lib/python3.13/dist-packages (0.11.1)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.18.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from jupysql) (2.0.54)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.6.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.13/dist-packages (from jupysql) (25.20.2)
Requirement already satisfied: jupysql-plugin>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.4.5)
Requirement already satisfied: ploomber-core>=0.2.7 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.2.27)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Requirement already satisfied: posthog>=3.0 in /usr/local/lib/python3.13/dist-packages (from ploomber-core>=0.2.7->jupysql) (7.60.1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=3.12.0->jupysql) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (4.16.0)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.4)
Requirement already satisfied: backoff>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.7.22)

In [3]:
%config SqlMagic.autopandas = True

In [4]:
%%sql

select *
from sales
limit  10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [5]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2              date
3           product
4             sales
5             store

In [6]:
%%sql
select  *
from sales
limit  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

Here are the `SELECT *` queries for each table in your database:

```sql
SELECT * FROM currencyexchange LIMIT 10;
```

```sql
SELECT * FROM customer LIMIT 10;
```

```sql
SELECT * FROM date LIMIT 10;
```

```sql
SELECT * FROM product LIMIT 10;
```

```sql
SELECT * FROM sales LIMIT 10;
```

```sql
SELECT * FROM store LIMIT 10;
```

In [7]:
%%sql
SELECT * FROM currencyexchange LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [8]:
%%sql
select *
from information_schema.columns
where table_name='customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [9]:
%%sql
select *
from sales limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [10]:
%%sql
select orderdate,
quantity * netprice * exchangerate as  NETREVENUE
FROM sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  netrevenue
0  2015-01-01       63.49
1  2015-01-01      423.28
2  2015-01-01      108.75
3  2015-01-01     1146.75
4  2015-01-01      950.25
5  2015-01-01     1302.91
6  2015-01-01       58.73
7  2015-01-01      224.98
8  2015-01-01      263.11
9  2015-01-01      578.52

recent sales >=2020

In [11]:
%%sql
select orderdate,
quantity * netprice * exchangerate as  NETREVENUE
FROM sales
where orderdate::date >='2020-01-01'
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  netrevenue
0  2020-01-01       99.47
1  2020-01-01      139.97
2  2020-01-01      669.39
3  2020-01-01     4090.60
4  2020-01-01      237.15
5  2020-01-01     1507.16
6  2020-01-01      189.35
7  2020-01-01      539.90
8  2020-01-01     5590.00
9  2020-01-01     3580.00

add product info

In [12]:
%%sql
select s.orderdate,s.quantity * s.netprice * s.exchangerate as  NETREVENUE,c.givenname,c.surname,c.countryfull,c.continent,p.productkey,p.productname,p.categoryname,p.subcategoryname,
CASE
  WHEN s.quantity * s.netprice * s.exchangerate >1000
  THEN 'HIGH' ELSE 'LOW'
END AS LOW_HIGH_ALIAS
from sales s
left  join customer c
on s.customerkey=c.customerkey
left join product p
on s.productkey=p.productkey
where orderdate::date >='2020-01-01'

limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,netrevenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,low_high_alias
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,LOW
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,LOW
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",LOW
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,HIGH
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,LOW
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves,HIGH
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games,LOW
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops,LOW
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops,HIGH
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors,HIGH

In [13]:
%%sql

SELECT
    c.countryfull,
    p.productname,
    p.categoryname,

    SUM(s.quantity * s.netprice * s.exchangerate) AS NETREVENUE,

    CASE
        WHEN SUM(s.quantity * s.netprice * s.exchangerate) > 1000
        THEN 'HIGH'
        ELSE 'LOW'
    END AS LOW_HIGH_ALIAS

FROM sales s

LEFT JOIN customer c
    ON s.customerkey = c.customerkey

LEFT JOIN product p
    ON s.productkey = p.productkey

WHERE s.orderdate::date >= '2020-01-01'

GROUP BY
    c.countryfull,
    p.productname,
    p.categoryname

LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,countryfull,productname,categoryname,netrevenue,low_high_alias
0,Australia,A. Datum Advanced Digital Camera M300 Black,Cameras and camcorders,2523.67,HIGH
1,Australia,A. Datum Advanced Digital Camera M300 Green,Cameras and camcorders,3391.85,HIGH
2,Australia,A. Datum Advanced Digital Camera M300 Grey,Cameras and camcorders,2965.63,HIGH
3,Australia,A. Datum Advanced Digital Camera M300 Orange,Cameras and camcorders,1466.61,HIGH
4,Australia,A. Datum Advanced Digital Camera M300 Pink,Cameras and camcorders,1304.54,HIGH
5,Australia,A. Datum All in One Digital Camera M200 Azure,Cameras and camcorders,264.97,LOW
6,Australia,A. Datum All in One Digital Camera M200 Black,Cameras and camcorders,1509.71,HIGH
7,Australia,A. Datum All in One Digital Camera M200 Green,Cameras and camcorders,1446.02,HIGH
8,Australia,A. Datum All in One Digital Camera M200 Grey,Cameras and camcorders,722.29,LOW
9,Australia,A. Datum All in One Digital Camera M200 Orange,Cameras and camcorders,557.35,LOW

In [14]:
%%sql
SELECT orderdate,count(customerkey) as totalcustomer
from sales
group by orderdate
order by orderdate desc

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  totalcustomer
0     2024-04-20             97
1     2024-04-19             50
2     2024-04-18             57
3     2024-04-17             61
4     2024-04-16             32
...          ...            ...
3289  2015-01-06             12
3290  2015-01-05             10
3291  2015-01-03             21
3292  2015-01-02              8
3293  2015-01-01             25

[3294 rows x 2 columns]

In [15]:
%%sql
SELECT orderdate,count(distinct(customerkey)) as totalcustomer
from sales
where orderdate::date between '2020-01-01' and '2020-12-31'
group by orderdate
order by orderdate desc;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

339 rows affected.

      orderdate  totalcustomer
0    2020-12-31             13
1    2020-12-30             12
2    2020-12-29              9
3    2020-12-28              7
4    2020-12-27              1
..          ...            ...
334  2020-01-05              5
335  2020-01-04             62
336  2020-01-03             34
337  2020-01-02             52
338  2020-01-01             46

[339 rows x 2 columns]

In [16]:
%%sql
SELECT s.orderdate,count(distinct(s.customerkey)) as totalcustomer,
count(DISTINCT
  CASE
    WHEN c.continent = 'Europe' then s.customerkey end) as eu_customers,
  count(distinct case when c.continent='North America' then c.customerkey end ) as na_customers,
  count(distinct case when c.continent='Australia' then c.customerkey end ) as as_customers
from sales s

left  join customer c
on s.customerkey=c.customerkey
where s.orderdate::date between '2023-01-01' and '2023-12-31'
group by s.orderdate
order by s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  totalcustomer  eu_customers  na_customers  as_customers
0    2023-01-01             12             6             5             1
1    2023-01-02             49            15            31             3
2    2023-01-03             64            17            44             3
3    2023-01-04             78            28            46             4
4    2023-01-05             87            22            57             8
..          ...            ...           ...           ...           ...
359  2023-12-27             73            26            41             6
360  2023-12-28             75            24            44             7
361  2023-12-29             55            19            32             4
362  2023-12-30             91            25            50            16
363  2023-12-31              9             1             8             0

[364 rows x 5 columns]

In [17]:
%%sql
SELECT
    p.categoryname,
    SUM(CASE WHEN EXTRACT(YEAR FROM s.orderdate) = 2022 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS total_revenue_2022,
    SUM(CASE WHEN EXTRACT(YEAR FROM s.orderdate) = 2023 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS total_revenue_2023
FROM sales s
LEFT JOIN product p
    ON s.productkey = p.productkey
WHERE EXTRACT(YEAR FROM s.orderdate) IN (2022, 2023)
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  total_revenue_2022  total_revenue_2023
0                          Audio           766938.21           688690.18
1        Cameras and camcorders           2382532.56          1983546.29
2                    Cell phones          8119665.07          6002147.63
3                      Computers         17862213.49         11650867.21
4                 Games and Toys           316127.30           270374.96
5                Home Appliances          6612446.68          5919992.87
6  Music, Movies and Audio Books          2989297.28          2180768.13
7                   TV and Video          5815336.61          4412178.23

 total net revenue by category (2022 vs 2023)

In [18]:
%%sql
select p.categoryname,SUM(s.quantity*s.netprice*s.exchangerate) as net_revenue ,
SUM(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as total_net_revenue_2022,
SUM(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as total_net_revenue_2023
from sales s
left  join product p on s.productkey=p.productkey
group by p.categoryname
order  by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,net_revenue,total_net_revenue_2022,total_net_revenue_2023
0,Audio,5312898.10,766938.21,688690.18
1,Cameras and camcorders,18520360.66,2382532.56,1983546.29
2,Cell phones,32624265.72,8119665.07,6002147.63
3,Computers,90619022.05,17862213.49,11650867.21
4,Games and Toys,1668574.13,316127.30,270374.96
5,Home Appliances,26607245.54,6612446.68,5919992.87
6,"Music, Movies and Audio Books",10588311.00,2989297.28,2180768.13
7,TV and Video,20466861.38,5815336.61,4412178.23

In [21]:
%%sql
select p.categoryname,
AVG(case
  when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as avg_2022_net_rev ,
AVG(case
  when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as avg_2023_net_rev
from sales s
left  join product p
on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname desc

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  avg_2022_net_rev  avg_2023_net_rev
0                   TV and Video            425.35            322.72
1  Music, Movies and Audio Books             93.37             68.11
2                Home Appliances            390.05            349.20
3                 Games and Toys             15.60             13.34
4                      Computers            384.13            250.55
5                    Cell phones            194.66            143.89
6        Cameras and camcorders             176.85            147.23
7                          Audio             50.18             45.06

In [22]:
%%sql
select p.categoryname,
AVG(case
  when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as avg_2022_net_rev ,
MIN(case
  when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as min_2022_net_rev ,
MAX(case
  when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as max_2022_net_rev ,
AVG(case
  when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as avg_2023_net_rev ,
MIN(case
  when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as min_2023_net_rev ,
MAX(case
  when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*exchangerate else 0 end) as max_2023_net_rev
from sales s
left  join product p
on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname desc

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_2022_net_rev,min_2022_net_rev,max_2022_net_rev,avg_2023_net_rev,min_2023_net_rev,max_2023_net_rev
0,TV and Video,425.35,0.00,30259.41,322.72,0.00,27503.12
1,"Music, Movies and Audio Books",93.37,0.00,5415.19,68.11,0.00,3804.91
2,Home Appliances,390.05,0.00,31654.55,349.20,0.00,32915.59
3,Games and Toys,15.60,0.00,5202.01,13.34,0.00,3357.30
4,Computers,384.13,0.00,38082.66,250.55,0.00,27611.60
5,Cell phones,194.66,0.00,7692.37,143.89,0.00,8912.22
6,Cameras and camcorders,176.85,0.00,15008.39,147.23,0.00,13572.00
7,Audio,50.18,0.00,3473.36,45.06,0.00,2730.87

In [23]:
%%sql
select
  PERCENTILE_CONT(0.5) within group (order by netprice) as md_price
  from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   md_price
0    191.95

In [27]:
%%sql
select p.categoryname,
PERCENTILE_CONT(0.5) within  group (order  by s.quantity*s.netprice*exchangerate) as md_price
from sales s
left  join product p
on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  md_price
0                          Audio    219.59
1        Cameras and camcorders     730.74
2                    Cell phones    459.88
3                      Computers    982.44
4                 Games and Toys     34.10
5                Home Appliances    696.08
6  Music, Movies and Audio Books    152.80
7                   TV and Video    682.83

In [34]:
%%sql
select p.categoryname as category,
PERCENTILE_CONT(0.5) within group (order by (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end)) as md_price_2022,
PERCENTILE_CONT(0.5) within group (order by (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end)) as md_price_2023
from sales s
left  join product p
on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  md_price_2022  md_price_2023
0                          Audio         257.21         266.59
1        Cameras and camcorders          651.46         672.60
2                    Cell phones         418.60         375.88
3                      Computers         809.70         657.18
4                 Games and Toys          33.78          32.62
5                Home Appliances         791.00         825.25
6  Music, Movies and Audio Books         186.58         159.63
7                   TV and Video         730.46         790.79

In [33]:
%%sql
select p.categoryname as category,
PERCENTILE_CONT(0.5) within group (order by s.quantity*s.netprice*s.exchangerate) FILTER (WHERE s.orderdate between '2022-01-01' and '2022-12-31') as md_price_2022,
PERCENTILE_CONT(0.5) within group (order by s.quantity*s.netprice*s.exchangerate) FILTER (WHERE s.orderdate between '2023-01-01' and '2023-12-31') as md_price_2023
from sales s
left  join product p
on s.productkey=p.productkey
group by p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  md_price_2022  md_price_2023
0                          Audio         257.21         266.59
1        Cameras and camcorders          651.46         672.60
2                    Cell phones         418.60         375.88
3                      Computers         809.70         657.18
4                 Games and Toys          33.78          32.62
5                Home Appliances         791.00         825.25
6  Music, Movies and Audio Books         186.58         159.63
7                   TV and Video         730.46         790.79

In [38]:
%%sql

SELECT
    p.categoryname AS category,

    PERCENTILE_CONT(0.5) WITHIN GROUP (
        ORDER BY (
            CASE
                WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
                THEN (s.quantity * s.netprice * s.exchangerate)
            END
        )
    ) AS y2022_median_sales,
PERCENTILE_CONT(0.5) within group (order  by( case when s.orderdate between '2023-01-01' and '2023-12-31' then (s.quantity * s.netprice * s.exchangerate)end)) y2023_median_sales

FROM sales s

LEFT JOIN product p
    ON s.productkey = p.productkey

GROUP BY
    p.categoryname

ORDER BY
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

adv  segemntationn

In [45]:
%%sql
select orderdate,quantity,netprice,
case when quantity>=2 and netprice >=50 then 'high' else 'standard order'
end as size

from sales
order by quantity desc
limit  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice            size
0  2015-01-31        10      5.91  standard order
1  2015-01-14        10    105.30            high
2  2015-01-29        10     45.43  standard order
3  2015-01-29        10    691.20            high
4  2015-01-05        10     43.47  standard order
5  2015-01-14        10    363.99            high
6  2015-01-15        10    325.25            high
7  2015-01-24        10    115.63            high
8  2015-01-01        10    152.00            high
9  2015-01-31        10    471.37            high

In [52]:
%%sql
select orderdate,quantity,netprice,
case
  when quantity >=2 and netprice >=100 then 'multiple  high value  items'
  when netprice >=100 then 'sinngle high value item'
  when quantity >=2 then 'multiple standard item'
  else 'single standard item'
end as size
from sales

order by quantity desc

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  quantity  netprice                         size
0       2018-05-29        10    163.99  multiple  high value  items
1       2017-03-04        10    257.56  multiple  high value  items
2       2017-12-05        10     21.07       multiple standard item
3       2017-02-11        10    101.69  multiple  high value  items
4       2015-11-04        10    399.20  multiple  high value  items
...            ...       ...       ...                          ...
199868  2023-12-23         1    219.00      sinngle high value item
199869  2024-02-06         1    589.00      sinngle high value item
199870  2023-12-23         1    129.00      sinngle high value item
199871  2023-12-23         1    268.00      sinngle high value item
199872  2023-12-23         1    119.99      sinngle high value item

[199873 rows x 4 columns]

In [54]:
%%sql

WITH sales_segment AS (

    SELECT
        quantity,
        CASE
            WHEN quantity >= 2 AND netprice >= 100
                THEN 'multiple high value items'

            WHEN netprice >= 100
                THEN 'single high value item'

            WHEN quantity >= 2
                THEN 'multiple standard item'

            ELSE 'single standard item'
        END AS size

    FROM sales
)

SELECT
    quantity,
    size,
    COUNT(*) AS total_count

FROM sales_segment

GROUP BY
    quantity,
    size

ORDER BY
    quantity desc,
    size desc ;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

    quantity                       size  total_count
0         10     multiple standard item         1036
1         10  multiple high value items         1840
2          9     multiple standard item         1020
3          9  multiple high value items         1818
4          8     multiple standard item         2150
5          8  multiple high value items         3696
6          7     multiple standard item         4196
7          7  multiple high value items         7344
8          6     multiple standard item         4186
9          6  multiple high value items         7439
10         5     multiple standard item         4235
11         5  multiple high value items         7448
12         4     multiple standard item         6296
13         4  multiple high value items        11093
14         3     multiple standard item        12513
15         3  multiple high value items        22002
16         2     multiple standard item        16000
17         2  multiple high value items        27693
18         1       single standard item        21141
19         1     single high value item        36727

In [55]:
%%sql
select PERCENTILE_CONT(0.5) WITHIN GROUP (order by (s.quantity*s.netprice*s.exchangerate)) as md
from sales s
where orderdate between '2022-01-01' and '2022-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

      md
0 421.34

In [58]:
%%sql

SELECT
    p.categoryname AS category,
  sum(case when (s.quantity*s.netprice*s.exchangerate)<421 then (s.quantity*s.netprice*s.exchangerate) end) as low_net_rev,
   sum(case when (s.quantity*s.netprice*s.exchangerate)>=421 then (s.quantity*s.netprice*s.exchangerate) end) as high_net_rev



FROM sales s

LEFT JOIN product p
    ON s.productkey = p.productkey

GROUP BY
    p.categoryname

ORDER BY
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  low_net_rev  high_net_rev
0                          Audio   1871494.23    3441403.87
1        Cameras and camcorders     897447.97   17622912.69
2                    Cell phones   3155920.57   29468345.15
3                      Computers   2472767.19   88146254.86
4                 Games and Toys   1276474.34     392099.80
5                Home Appliances   1212015.40   25395230.13
6  Music, Movies and Audio Books   3024662.59    7563648.40
7                   TV and Video   1070330.77   19396530.61

In [60]:
%%sql

SELECT
    p.categoryname AS category,
  sum(case when (s.quantity*s.netprice*s.exchangerate)<421
  and orderdate between '2022-01-01' and '2022-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as low_net_rev_2022,

   sum(case when (s.quantity*s.netprice*s.exchangerate)>=421
   and  orderdate between '2022-01-01' and '2022-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as high_net_rev_2022,

    sum(case when (s.quantity*s.netprice*s.exchangerate)<421
  and orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as low_net_rev_2023,

   sum(case when (s.quantity*s.netprice*s.exchangerate)>=421
   and  orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as high_net_rev_2023



FROM sales s

LEFT JOIN product p
    ON s.productkey = p.productkey

GROUP BY
    p.categoryname

ORDER BY
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_rev_2022,high_net_rev_2022,low_net_rev_2023,high_net_rev_2023
0,Audio,238169.78,528768.44,198129.16,490561.03
1,Cameras and camcorders,144049.62,2238482.94,111391.79,1872154.49
2,Cell phones,890646.37,7229018.70,787293.12,5214854.52
3,Computers,696756.78,17165456.71,647824.37,11003042.84
4,Games and Toys,236034.02,80093.29,211055.99,59318.98
5,Home Appliances,250024.50,6362422.18,197026.65,5722966.22
6,"Music, Movies and Audio Books",727216.61,2262080.67,613756.03,1567012.10
7,TV and Video,296156.18,5519180.43,182957.82,4229220.41

In [64]:
%%sql
with median_value  as(
select PERCENTILE_CONT(0.5) WITHIN GROUP (order by (s.quantity*s.netprice*s.exchangerate)) as md
from sales s
where orderdate between '2022-01-01' and '2022-12-31'
)


SELECT
    p.categoryname AS category,
  sum(case when (s.quantity*s.netprice*s.exchangerate)< md
  and orderdate between '2022-01-01' and '2022-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as low_net_rev_2022,

   sum(case when (s.quantity*s.netprice*s.exchangerate)>= md
   and  orderdate between '2022-01-01' and '2022-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as high_net_rev_2022,

    sum(case when (s.quantity*s.netprice*s.exchangerate)< md
  and orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as low_net_rev_2023,

   sum(case when (s.quantity*s.netprice*s.exchangerate)>= md
   and  orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity*s.netprice*s.exchangerate) end) as high_net_rev_2023



FROM sales s

LEFT JOIN product p
    ON s.productkey = p.productkey, median_value  mv

GROUP BY
    p.categoryname

ORDER BY
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_rev_2022,high_net_rev_2022,low_net_rev_2023,high_net_rev_2023
0,Audio,239854.58,527083.64,198129.16,490561.03
1,Cameras and camcorders,144049.62,2238482.94,111391.79,1872154.49
2,Cell phones,891488.91,7228176.16,788135.50,5214012.13
3,Computers,698441.60,17163771.89,647824.37,11003042.84
4,Games and Toys,236034.02,80093.29,211477.19,58897.78
5,Home Appliances,250024.50,6362422.18,197026.65,5722966.22
6,"Music, Movies and Audio Books",727637.76,2261659.52,613756.03,1567012.10
7,TV and Video,296156.18,5519180.43,182957.82,4229220.41

In [78]:
%%sql

WITH percentile AS (

    SELECT
        PERCENTILE_CONT(0.25) WITHIN GROUP (
            ORDER BY (s.quantity * s.netprice * s.exchangerate)
        ) AS reve_25TH_percentile,

        PERCENTILE_CONT(0.75) WITHIN GROUP (
            ORDER BY (s.quantity * s.netprice * s.exchangerate)
        ) AS reve_75TH_percentile

    FROM sales s

    WHERE orderdate BETWEEN '2022-01-01' AND '2022-12-31'
)

SELECT
    p.categoryname AS category,
    case
      when (s.quantity * s.netprice * s.exchangerate) <= perc.reve_25TH_percentile then '3-low'
      when (s.quantity * s.netprice * s.exchangerate) >= perc.reve_75TH_percentile then '1-high'
      else '2-medium'
    end as revenue_tier,
    SUM(s.quantity * s.netprice * s.exchangerate) as total_revenue

FROM sales s

LEFT JOIN product p
    ON s.productkey = p.productkey,

percentile perc

GROUP BY p.categoryname,revenue_tier

ORDER BY category,revenue_tier;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio       1-high     1089077.23
1                           Audio     2-medium     3923515.28
2                           Audio        3-low      300305.59
3         Cameras and camcorders        1-high    14812098.11
4         Cameras and camcorders      2-medium     3620129.66
5         Cameras and camcorders         3-low       88132.89
6                     Cell phones       1-high    21097917.93
7                     Cell phones     2-medium    11084005.46
8                     Cell phones        3-low      442342.32
9                       Computers       1-high    78673147.18
10                      Computers     2-medium    11718071.03
11                      Computers        3-low      227803.84
12                 Games and Toys       1-high      126142.52
13                 Games and Toys     2-medium      972817.54
14                 Games and Toys        3-low      569614.07
15                Home Appliances       1-high    22078783.26
16                Home Appliances     2-medium     4406311.76
17                Home Appliances        3-low      122150.51
18  Music, Movies and Audio Books       1-high     3620272.71
19  Music, Movies and Audio Books     2-medium     6280497.41
20  Music, Movies and Audio Books        3-low      687540.88
21                   TV and Video       1-high    16372785.73
22                   TV and Video     2-medium     4012155.06
23                   TV and Video        3-low       81920.60

date  format

In [90]:
%%sql
select
DATE_TRUNC('month',orderdate)::date as order_month,
sum(quantity*netprice*exchangerate) as net_revenue,

count(distinct(customerkey)) as total_customer_unique
from sales
group by order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_customer_unique
0    2015-01-01    384092.66                    200
1    2015-02-01    706374.12                    291
2    2015-03-01    332961.59                    139
3    2015-04-01    160767.00                     78
4    2015-05-01    548632.63                    236
..          ...          ...                    ...
107  2023-12-01   2928550.93                   1484
108  2024-01-01   2677498.55                   1340
109  2024-02-01   3542322.55                   1718
110  2024-03-01   1692854.89                    877
111  2024-04-01    483851.39                    246

[112 rows x 3 columns]

In [92]:
%%sql
select to_char(orderdate,'yyyy-mm')
from sales
limit  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   to_char
0  2015-01
1  2015-01
2  2015-01
3  2015-01
4  2015-01
5  2015-01
6  2015-01
7  2015-01
8  2015-01
9  2015-01

In [93]:
%%sql
select orderdate,
date_part('year',orderdate) as order_year,
date_part('month',orderdate) as order_month,
date_part('day',orderdate) as order_day,
date_part('dow',orderdate) as order_day_of_week
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  order_year  order_month  order_day  order_day_of_week
0       2015-01-01     2015.00         1.00       1.00               4.00
1       2015-01-01     2015.00         1.00       1.00               4.00
2       2015-01-01     2015.00         1.00       1.00               4.00
3       2015-01-01     2015.00         1.00       1.00               4.00
4       2015-01-01     2015.00         1.00       1.00               4.00
...            ...         ...          ...        ...                ...
199868  2024-04-20     2024.00         4.00      20.00               6.00
199869  2024-04-20     2024.00         4.00      20.00               6.00
199870  2024-04-20     2024.00         4.00      20.00               6.00
199871  2024-04-20     2024.00         4.00      20.00               6.00
199872  2024-04-20     2024.00         4.00      20.00               6.00

[199873 rows x 5 columns]

# New section

In [97]:
%%sql
select orderdate,
extract(year from orderdate) as YEAR,
extract(month from orderdate) as month ,
extract(day from orderdate) as day,
extract(dow from orderdate) as day_of_week
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  year month day day_of_week
0       2015-01-01  2015     1   1           4
1       2015-01-01  2015     1   1           4
2       2015-01-01  2015     1   1           4
3       2015-01-01  2015     1   1           4
4       2015-01-01  2015     1   1           4
...            ...   ...   ...  ..         ...
199868  2024-04-20  2024     4  20           6
199869  2024-04-20  2024     4  20           6
199870  2024-04-20  2024     4  20           6
199871  2024-04-20  2024     4  20           6
199872  2024-04-20  2024     4  20           6

[199873 rows x 5 columns]

In [106]:
%%sql

SELECT
    EXTRACT(YEAR FROM orderdate) AS yr_ord,
    EXTRACT(MONTH FROM orderdate) AS mnth_ord,
    SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
WHERE EXTRACT(YEAR FROM orderdate) = '2023'
GROUP BY yr_ord, mnth_ord
ORDER BY yr_ord, mnth_ord;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   yr_ord mnth_ord  net_revenue
0    2023        1   3664431.34
1    2023        2   4465204.57
2    2023        3   2244316.52
3    2023        4   1162796.16
4    2023        5   2943005.99
5    2023        6   2864500.03
6    2023        7   2337639.34
7    2023        8   2623919.79
8    2023        9   2622774.85
9    2023       10   2551322.61
10   2023       11   2700103.38
11   2023       12   2928550.93

In [108]:
%%sql
select current_date,
extract(year from orderdate) as order_year,
extract(year from current_date) as current_year,
EXTRACT(year from current_date) - 5 as five_year_ago,
s.orderdate,p.categoryname
from sales s
left join product p on s.productkey=p.productkey
where extract(year from orderdate) >=extract(year from current_date) - 5
group by s.orderdate,p.categoryname
order by s.orderdate ,p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

,current_date,order_year,current_year,five_year_ago,orderdate,categoryname
0,2026-09-29,2021,2026,2021,2021-01-01,Audio
1,2026-09-29,2021,2026,2021,2021-01-01,Cameras and camcorders
2,2026-09-29,2021,2026,2021,2021-01-01,Cell phones
3,2026-09-29,2021,2026,2021,2021-01-01,Computers
4,2026-09-29,2021,2026,2021,2021-01-01,Games and Toys
...,...,...,...,...,...,...
8952,2026-09-29,2024,2026,2021,2024-04-20,Computers
8953,2026-09-29,2024,2026,2021,2024-04-20,Games and Toys
8954,2026-09-29,2024,2026,2021,2024-04-20,Home Appliances
8955,2026-09-29,2024,2026,2021,2024-04-20,"Music, Movies and Audio Books"
8956,2026-09-29,2024,2026,2021,2024-04-20,TV and Video